<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-13T21:28:23 IST" name="Failed suite [Suite]" finished-at="2022-07-13T21:28:24 IST" duration-ms="236">
    <groups>
      <group name="Smoke">
        <method signature="carloan2.carloan2Vr1(java.lang.String)[pri:0, instance:testng.carloan2@a2431d0]" name="carloan2Vr1" class="testng.carloan2"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-07-13T21:28:23 IST" name="SmokeTest(failed)" finished-at="2022-07-13T21:28:24 IST" duration-ms="236">
      <class name="testng.carloan2">
        <test-method signature="carloan2Vr1(java.lang.String)[pri:0, instance:testng.carloan2@a2431d0]" started-at="2022-07-13T21:28:24 IST" name="carloan2Vr1" finished-at="2022-07-13T21:28:24 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'url' is required by @Test on method carloan2Vr1 but has not been marked @Optional or defined
in C:\Users\ELCOT\Documents\Selenium\TestNG\test-output\testng-failed.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'url' is required by @Test on method carloan2Vr1 but has not been marked @Optional or defined
in C:\Users\ELCOT\Documents\Selenium\TestNG\test-output\testng-failed.xml
at org.testng.internal.Parameters.createParams(Parameters.java:270)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:358)
at org.testng.internal.Parameters.createParameters(Parameters.java:700)
at org.testng.internal.Parameters.handleParameters(Parameters.java:884)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carloan2Vr1 -->
      </class> <!-- testng.carloan2 -->
    </test> <!-- SmokeTest(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
